# Wallpaper setup!
# To reload when you update config: Run `killall hyprpaper` and then `hyperpaper & disown`

# run `hyprctl monitors all` to see all your monitors!!! In order to create your setup.

# preload = /home/username/Wallpapers/example.png

# wallpaper = DP-1,/home/username/Wallpapers/example.png
# wallpaper = DP-3,/home/username/Wallpapers/example.png

[Settings]
language = en
folder = /home/aura/Pictures/wallpaper
preload = /home/aura/Pictures/wallpaper/HIRAETH.png
wallpaper = /home/aura/Pictures/wallpaper/HIRAETH.png
backend = hyprpaper
monitors = All
fill = fill
sort = name
color = #ffffff
subfolders = True
show_hidden = False
show_gifs_only = False
post_command = ~/.config/waypaper/wallpaper.sh "$wallpaper"