# ========
#
# ========

$HYPRDOTS = /home/aura/.dotfiles/common/hypr


source = $HYPRDOTS/variables.conf # Programs and directories used throughout the config
source = $HYPRDOTS/monitor.conf # Monitor settings
source = $HYPRDOTS/env.conf # Environment variables
source = $HYPRDOTS/input.conf # Keyboard settings
source = $HYPRDOTS/design.conf # Window design. Should be changed based on the dotfile selection

source = $HYPRDOTS/keybinds.conf # Keybindings of the config
source = $HYPRDOTS/workspaces.conf # Workspace related settings

source = $HYPRDOTS/plugins.conf # Plugin configuration, only hyprscrsolling for now

source = $HYPRDOTS/windowRules.conf # Certain window have extra rules for usability or bugfixing

source = $HYPRDOTS/startup.conf # Startup apps