# ========
#   Hyprland config file for my "diinki aero" rice. Hyprland is the right tool for the job due to all of its available
#   window effects, but you could achieve 99% of the same design with swayfx as well; I just chose hyprland due to
#   compatability issues with nvidia GPU.
# ========

$HOME = /home/aura

#                                    !!MONITORS!!                                   #
# --------------------------------------------------------------------------------- #
#                                    !!MONITORS!!                                   #

# Make sure to customize monitors! This is just my setup so you get an idea.
# run `hyprctl monitors all` to see all your monitors!!!


source = $HOME/.dotfiles/common/hypr/monitor.conf

# Customize the wallpapers in hyprpaper.conf ^-^


# Startup programs, these are mine, most likely you'll have these as well.

# Network Manager icon on waybar
#exec-once = nm-applet
# Wallpaper manager
exec-once = hyprpaper
# Authentication manager
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# Waybar, top bar
exec-once = waybar
# Clipboard history
exec-once = wl-paste --watch cliphist store
# Widget start
exec-once = /home/aura/.configs/eww/scripts/start.sh
# Start pw-loopback to route audio from line in to main sink
exec-once = pactl load-module module-loopback




# Default programs, these are what I prefer.
$terminal = kitty
$fileManager = GTK_THEME=diinki-retro-dark caja
$menu = pgrep wofi > /dev/null 2>&1 && killall wofi || wofi --show drun
$browser = GTK_THEME=diinki-retro-dark librewolf


# Environment variables
source = $HOME/.dotfiles/common/hypr/env.conf



#                                    !!INPUT!!                                      #
# --------------------------------------------------------------------------------- #
#                                    !!INPUT!!                                      #

# READ https://wiki.hyprland.org/Configuring/Variables/#input IF CONFUSED!
# Example keyboard/mouse input settings.

source = $HOME/.dotfiles/common/hypr/input.conf


#                                    !!DESIGN!!                                     #
# --------------------------------------------------------------------------------- #
#                                    !!DESIGN!!                                     #

source = $HOME/.dotfiles/common/hypr/design.conf


#                                    !!KEYBINDS!!                                   #
# --------------------------------------------------------------------------------- #
#                                    !!KEYBINDS!!                                   #

# My personally preferred keybinds, change as needed.
source = $HOME/.dotfiles/common/hypr/keybinds.conf
source = $HOME/.dotfiles/common/hypr/workspaces.conf




#                                    !!WINDOW RULES!!                               #
# --------------------------------------------------------------------------------- #
#                                    !!WINDOW RULES!!                               #


# These window rules are fixes to bugs that certain programs I use have, add more as
# you see fit.


source = $HOME/.dotfiles/common/hypr/windowRules.conf

# Add blur to waybar
layerrule = blur, waybar
layerrule = blurpopups, waybar
layerrule = ignorealpha 0.7, waybar

layerrule = blur, wofi
layerrule = blurpopups, wofi
layerrule = ignorealpha 0.7, wofi


# Fix dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0