# Wallpaper setup!
# To reload when you update config: Run `killall hyprpaper` and then `hyperpaper & disown`

# run `hyprctl monitors all` to see all your monitors!!! In order to create your setup.

preload = /home/aura/Pictures/wallpaper/8zyadltp691g1.jpeg
preload = /home/aura/Pictures/wallpaper/Gx1Wl8BWEAAcJH6.jpg
preload = /home/aura/Pictures/wallpaper/moika/16_9_wallpaper.png
preload = /home/aura/Pictures/wallpaper/.nsfw/DVa_Sunset_02.png

wallpaper = DP-1,/home/aura/Pictures/wallpaper/8zyadltp691g1.jpeg
wallpaper = DP-2,/home/aura/Pictures/wallpaper/Gx1Wl8BWEAAcJH6.jpg
wallpaper = HDMI-A-1,/home/aura/Pictures/wallpaper/moika/16_9_wallpaper.png
wallpaper = TAB,/home/aura/Pictures/wallpaper/.nsfw/DVa_Sunset_02.png