#                                    !!DESIGN!!                                     #
# --------------------------------------------------------------------------------- #
#                                    !!DESIGN!!                                     #
animations {
    enabled = true

    bezier = myBezier, 0, 1, 0.1, 1.0
    bezier = overshoot, 0, 1, 0.1, 1.15

    animation = windows, 1, 1.5, myBezier
    animation = windowsOut, 1, 2, myBezier, popin 95%
    animation = border, 1, 12, myBezier
    animation = borderangle, 1, 5, default
    animation = fade, 1, 6, default
    animation = workspaces, 1, 6, myBezier, slidevert

    #slide -> normal slide
    #slidevert
    #fade
    #slidefade
    #slidefadevert

    # Make special workspaces appear from the top
    animation = specialWorkspace, 1, 6, default, slidefadevert -50%
}

# The gaps between windows, as well as border colors.
# proportional to the taskbar values.
general {
    # Layout control
    layout = scrolling


    # Inner and Outer gaps between windows.
    gaps_in = 5
    gaps_out = 8

    # I prefer a thin border
    border_size = 1

    # Border colors.
    col.active_border = rgb(AC82E9)
    col.inactive_border = rgb(d8cab8)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true


    # READ https://wiki.hyprland.org/Configuring/Tearing/ BEFORE TURNING ON!
    allow_tearing = false
}

# Window Decorations! Shadow, Blur, etc.
decoration {
    rounding = 6

    # I want transparancy to not change, since we have the colored border.
    active_opacity = 1.0
    inactive_opacity = 1

    # Window Shadow
    shadow:enabled = true
    shadow:range = 16
    shadow:render_power = 5
    shadow:color = rgba(0,0,0,0.2)

    # Transparent Window Blur
    blur:enabled = true

    blur:new_optimizations = true
    blur:size = 2
    blur:passes = 3
    blur:vibrancy = 0.1696
}

# Read https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more info on dwindle layout.
dwindle {
    pseudotile = true
    preserve_split = true
}

# Read https://wiki.hyprland.org/Configuring/Master-Layout/ for more info on master layout.
master {
    new_status = slave
}


# No need for gestures unless you have a touch display.
#gestures {
#    swipe = false
#}