#                                    !!KEYBINDS!!                                   #
# --------------------------------------------------------------------------------- #
#                                    !!KEYBINDS!!                                   #



# mod + enter = start terminal
bind = $mainMod, Return, exec, $terminal
# mod + KP enter = other terminal
bind = $mainMod, KP_Enter, exec, cool-retro-term
# mod + Q = kill current focused application
bind = $mainMod, Q, killactive,
# mod + E = open file manager (I prefer caja).
bind = $mainMod, E, exec, $fileManager
# mod + shift + space = Toggle focused window to be floating or tiled.
### bind = $mainMod SHIFT, SPACE, togglefloating
bind = $mainMod, T, togglefloating
# mod + F = toggle focused window to full-screen view.
bind = $mainMod, F, fullscreen
# mod + D = toggle application launcher (I prefer wofi).
bind = $mainMod, D, exec, $menu
# mod + B = open browser (I like librewolf (based))
bind = $mainMod, B, exec, $browser
# mod + C = toggle CRT shader
bind = $mainMod, C, exec, hyprshade toggle $HOME/.dotfiles/common/shaders/crt_hypr_sl.frags


# mod + shift + S = take screenshot of area, MUST HAVE HYPRSHOT INSTALLED!
bind = $mainMod SHIFT, S, exec, hyprshot --mode region --output-folder /tmp
# PRINT = print the current monitor
bind = , PRINT, exec, hyprshot -m output --output-folder /tmp


# mod + V = open clipboard history (i'm gonna kill john linux)
bind = $mainMod, V, exec, $HOME/.dotfiles/common/scripts/cliphist.sh
# mod + Z = open mission center
bind = $mainMod, Z, exec, missioncenter
# mod + P = toggle pseudo
bind = $mainMod, P, pseudo
# Toggle split
bind = $mainMod, J, togglesplit

