#                                    !!MONITORS!!                                   #
# --------------------------------------------------------------------------------- #
#                                    !!MONITORS!!                                   #



#monitor = DP-1, 2560x1440@144, 0x0, 1, vrr, 3#, bitdepth, 10#, cm, auto
#monitor = DP-2, 1920x1080@60, 640x-1080, 1
#monitor = HDMI-A-1, 1920x1080@60, -1920x180, 1
#monitor = TAB, 1024x600, 2560x0, 0.8


monitorv2 { # main monitor (middle one)
  output = DP-1
  mode = 2560x1440@144
  position = 0x0
  scale = 1
  vrr = 3
  #bitdepth = 10 #hdr. may or may not work (probably won't)
  #cm = auto
}


monitorv2 { # second monitor (left one)
  output = HDMI-A-1
  mode = 1920x1080@60
  position = -1920x180
  scale = 1
}

monitorv2 { # third monitor (upper one)
  output = DP-2
  mode = 1920x1080@60
  position = 640x-1080
  scale = 1
}

monitorv2 { # tablet (to the right, sometimes)
  output = TAB
  mode = 1024x600@30
  position = 2560x0
  #transform = 3 #if this is active, vertical
  scale = 0.8
}

xwayland {
force_zero_scaling = true
}
