#                                    !!STARTUP!!                                     #
# ---------------------------------------------------------------------------------- #
#                                    !!STARTUP!!                                     #



# Startup programs, these are mine, most likely you'll have these as well.

# Network Manager icon on waybar
#exec-once = nm-applet
# Wallpaper manager
exec-once = hyprpaper
# Authentication manager
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# Waybar, top bar
exec-once = waybar
# Clipboard history
exec-once = wl-paste --watch cliphist store
# Widget start
# exec-once = /home/aura/.configs/eww/scripts/start.sh
# Start pw-loopback to route audio from line in to main sink
exec-once = pactl load-module module-loopback

