#                                   !!VARIABLES!!                                   #
# --------------------------------------------------------------------------------- #
#                                   !!VARIABLES!!                                   #

$HOME = /home/aura
$SCRIPTS = $HOME/.dotfiles/common/scripts

# Windows key / Super key is the main modifier key. (abbreviated as mod)
$mainMod = SUPER

# Default programs, these are what I prefer.
$terminal = kitty
$musicTerminal = kitty --class music
$fileManager = GTK_THEME=diinki-retro-dark caja
$menu = pgrep wofi > /dev/null 2>&1 && killall wofi || wofi --show drun
$browser = GTK_THEME=diinki-retro-dark librewolf
$fileEditor = codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland

#--------------------------------------------------------------
# Macropad keys abbreviation
#--------------------------------------------------------------
$MP1 = comma            # ,
$MP2 = period           # .
$MP3 = minus            # -
$MP4 = ntilde           # ñ
$MP5 = plus             # +
$MP6 = ccedilla         # ç
$MPCW = Page_Up         # PageUp
$MPCCW = Page_Down      # PageDown
$MPK = KP_Equal         # KP =
#--------------------------------------------------------------