#                                    !!WINDOW RULES!!                               #
# --------------------------------------------------------------------------------- #
#                                    !!WINDOW RULES!!                               #


# -- Some of my personally preferred window rules, you will probably like these as well! ---%
# -- There's also lots of bug-fixes for specific apps here.                              ---%

# Read https://wiki.hyprland.org/Configuring/Window-Rules/ for more info
# Read https://wiki.hyprland.org/Configuring/Workspace-Rules/  for more info


# I want certain apps to be floating by default when starting them.
# You can copy/paste this format and add your own preferred applications.
##windowrule = float, class:^(kitty)$
windowrule = float, class:^(waypaper)$

##windowrule = size 940 925, class:^(caja)$
##windowrule = float, class:^(caja)$

windowrule = size 700 600, class:^(org.pulseaudio.pavucontrol)$
windowrule = float, class:^(org.pulseaudio.pavucontrol)$

windowrule = float, class:^(qalculate-gtk)$